version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILD_COMMAND=${BUILD_COMMAND}
    image: server-entrenaly
    ports: 
      - 8081:8081
    depends_on:
      - db
    volumes:
      - .:/usr/src/app:delegated
    environment:
      PORT: ${PORT}
      NODE_ENV: ${NODE_ENV}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: db
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_URL: ${POSTGRES_URL}
  db:
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
